/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.turnyur.mycalculator;

/**
 *
 * @author Turnyur Siy
 */
public class MyCalculator extends javax.swing.JFrame {
         // Variables
   private static Double totalFirst=0.0;
    private static Double totalLast=0.0;
    static Character mathOperator='N';
    static int flag;
    /**
     * Creates new form MyCalculator
     */
    public MyCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDisplay = new javax.swing.JTextField();
        btnNine = new javax.swing.JPanel();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnEqu = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSine = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnCL = new javax.swing.JButton();
        txtDisplayOne = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Turnyur Technologies");
        setBackground(new java.awt.Color(51, 102, 255));

        txtDisplay.setEditable(false);
        txtDisplay.setBackground(new java.awt.Color(238, 238, 238));
        txtDisplay.setFont(new java.awt.Font("Kalinga", 0, 36)); // NOI18N
        txtDisplay.setForeground(new java.awt.Color(51, 51, 255));
        txtDisplay.setText(" ");

        btnNine.setBackground(new java.awt.Color(51, 51, 51));

        btnOne.setBackground(new java.awt.Color(0, 0, 0));
        btnOne.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOne.setForeground(new java.awt.Color(255, 255, 255));
        btnOne.setText("1");
        btnOne.setPreferredSize(new java.awt.Dimension(50, 20));
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnTwo.setBackground(new java.awt.Color(0, 0, 0));
        btnTwo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTwo.setForeground(new java.awt.Color(255, 255, 255));
        btnTwo.setText("2");
        btnTwo.setMaximumSize(new java.awt.Dimension(100, 100));
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnThree.setBackground(new java.awt.Color(0, 0, 0));
        btnThree.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThree.setForeground(new java.awt.Color(255, 255, 255));
        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(0, 0, 0));
        btnDiv.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(255, 255, 255));
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnFour.setBackground(new java.awt.Color(0, 0, 0));
        btnFour.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFour.setForeground(new java.awt.Color(255, 255, 255));
        btnFour.setText("4");
        btnFour.setPreferredSize(new java.awt.Dimension(50, 20));
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setBackground(new java.awt.Color(0, 0, 0));
        btnFive.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFive.setForeground(new java.awt.Color(255, 255, 255));
        btnFive.setText("5");
        btnFive.setMaximumSize(new java.awt.Dimension(100, 100));
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setBackground(new java.awt.Color(0, 0, 0));
        btnSix.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSix.setForeground(new java.awt.Color(255, 255, 255));
        btnSix.setText("6");
        btnSix.setMaximumSize(new java.awt.Dimension(100, 100));
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnMul.setBackground(new java.awt.Color(0, 0, 0));
        btnMul.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnMul.setForeground(new java.awt.Color(255, 255, 255));
        btnMul.setText("x");
        btnMul.setMaximumSize(new java.awt.Dimension(100, 100));
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });

        btnSeven.setBackground(new java.awt.Color(0, 0, 0));
        btnSeven.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSeven.setForeground(new java.awt.Color(255, 255, 255));
        btnSeven.setText("7");
        btnSeven.setMaximumSize(new java.awt.Dimension(100, 100));
        btnSeven.setPreferredSize(new java.awt.Dimension(50, 20));
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnEight.setBackground(new java.awt.Color(0, 0, 0));
        btnEight.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEight.setForeground(new java.awt.Color(255, 255, 255));
        btnEight.setText("8");
        btnEight.setMaximumSize(new java.awt.Dimension(100, 100));
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("9");
        jButton11.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        btnSub.setBackground(new java.awt.Color(0, 0, 0));
        btnSub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSub.setForeground(new java.awt.Color(255, 255, 255));
        btnSub.setText("-");
        btnSub.setMaximumSize(new java.awt.Dimension(100, 100));
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });

        btnPoint.setBackground(new java.awt.Color(0, 0, 0));
        btnPoint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPoint.setForeground(new java.awt.Color(255, 255, 255));
        btnPoint.setText(".");
        btnPoint.setMaximumSize(new java.awt.Dimension(100, 100));
        btnPoint.setPreferredSize(new java.awt.Dimension(50, 20));
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });

        btnZero.setBackground(new java.awt.Color(0, 0, 0));
        btnZero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnZero.setForeground(new java.awt.Color(255, 255, 255));
        btnZero.setText("0");
        btnZero.setMaximumSize(new java.awt.Dimension(100, 100));
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnEqu.setBackground(new java.awt.Color(0, 0, 0));
        btnEqu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEqu.setForeground(new java.awt.Color(255, 255, 255));
        btnEqu.setText("=");
        btnEqu.setMaximumSize(new java.awt.Dimension(100, 100));
        btnEqu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("+");
        btnAdd.setMaximumSize(new java.awt.Dimension(100, 100));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSine.setBackground(new java.awt.Color(0, 0, 0));
        btnSine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSine.setForeground(new java.awt.Color(255, 255, 255));
        btnSine.setText("sin");
        btnSine.setMaximumSize(new java.awt.Dimension(100, 100));
        btnSine.setPreferredSize(new java.awt.Dimension(50, 20));
        btnSine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSineActionPerformed(evt);
            }
        });

        btnCos.setBackground(new java.awt.Color(0, 0, 0));
        btnCos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCos.setForeground(new java.awt.Color(255, 255, 255));
        btnCos.setText("cos");
        btnCos.setMaximumSize(new java.awt.Dimension(100, 100));
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        btnLog.setBackground(new java.awt.Color(0, 0, 0));
        btnLog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLog.setForeground(new java.awt.Color(255, 255, 255));
        btnLog.setText("log");
        btnLog.setMaximumSize(new java.awt.Dimension(100, 100));
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnCL.setBackground(new java.awt.Color(0, 0, 0));
        btnCL.setForeground(new java.awt.Color(255, 255, 255));
        btnCL.setText("CL");
        btnCL.setMaximumSize(new java.awt.Dimension(100, 100));
        btnCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnNineLayout = new javax.swing.GroupLayout(btnNine);
        btnNine.setLayout(btnNineLayout);
        btnNineLayout.setHorizontalGroup(
            btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNineLayout.createSequentialGroup()
                .addComponent(btnSine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnNineLayout.createSequentialGroup()
                .addGroup(btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnNineLayout.createSequentialGroup()
                        .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEqu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnNineLayout.createSequentialGroup()
                        .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnNineLayout.createSequentialGroup()
                        .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnNineLayout.createSequentialGroup()
                        .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnNineLayout.createSequentialGroup()
                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        btnNineLayout.setVerticalGroup(
            btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNineLayout.createSequentialGroup()
                .addGroup(btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMul, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnFive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEqu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnNineLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(btnNineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(btnLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        txtDisplayOne.setEditable(false);
        txtDisplayOne.setBackground(new java.awt.Color(0, 0, 0));
        txtDisplayOne.setFont(new java.awt.Font("Terminator Two", 0, 12)); // NOI18N
        txtDisplayOne.setForeground(new java.awt.Color(0, 153, 0));
        txtDisplayOne.setText("  Turnyur Softwares");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDisplay)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtDisplayOne, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDisplayOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private static void getOperator(char txtDisplay ){
         mathOperator=txtDisplay ;
         
    }
    
   private static void setFlag(){
       flag=1;
   }
   
   private static void deactivateFlag(){
       flag=0;
   }
    
   
    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        // TODO add your handling code here:
        clearScreen(); 
        String showDisplay= txtDisplay.getText()+btnFive.getText();
         
             txtDisplay.setText(showDisplay);
             
             deactivateFlag();
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        clearScreen();   
        String showDisplay= txtDisplay.getText()+btnOne.getText();
             txtDisplay.setText(showDisplay);
            
              
            deactivateFlag();
    }//GEN-LAST:event_btnOneActionPerformed

    private void clearScreen() {
        // TODO add your handling code here:
        if(flag==1)txtDisplay.setText("");
    }

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        // TODO add your handling code here:
        clearScreen(); 
        String showDisplay= txtDisplay.getText()+btnSix.getText();
             txtDisplay.setText(showDisplay);
             
             deactivateFlag();
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        // TODO add your handling code here:
        clearScreen(); 
        String showDisplay= txtDisplay.getText()+btnTwo.getText();
             txtDisplay.setText(showDisplay);
             
             deactivateFlag();
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        // TODO add your handling code here:
        clearScreen(); 
        String showDisplay= txtDisplay.getText()+btnThree.getText();
        
             txtDisplay.setText(showDisplay);
             
             deactivateFlag();
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
          String initString=txtDisplay.getText();
          char firstIndex=initString.charAt(0) ;
        if(firstIndex== 's'   ){
            txtDisplay.setText("0");
            setFlag();
        }else if(firstIndex== 'c' ){
            txtDisplay.setText("0");
            setFlag();
        }else if(firstIndex== 'l' ){
            txtDisplay.setText("0");
            setFlag();
        } else if(initString=="0" ){
            txtDisplay.setText("0");
            setFlag();
        } 
        else if(firstIndex== '0' ){
            txtDisplay.setText("0");
            setFlag();
        }
        else{
        totalFirst= Double.parseDouble(txtDisplay.getText() );
         
        String showDisplay= txtDisplay.getText()+btnDiv.getText();
            txtDisplay.setText(showDisplay);
             getOperator('/' );
             }
             
           deactivateFlag();
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        // TODO add your handling code here:
        clearScreen(); 
        String showDisplay= txtDisplay.getText()+btnFour.getText();
             txtDisplay.setText(showDisplay);
             
             deactivateFlag();
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        // TODO add your handling code here:
        String initString=txtDisplay.getText();
        
         char firstIndex=initString.charAt(0) ;
        if(firstIndex== 's'   ){
            txtDisplay.setText("0");
            setFlag();
        }else if(firstIndex== 'c' ){
            txtDisplay.setText("0");
            setFlag();
        }else if(firstIndex== 'l' ){
            txtDisplay.setText("0");
            setFlag();
        } else if(initString=="0" ){
            txtDisplay.setText("0");
            setFlag();
        } else if(firstIndex== '0' ){
            txtDisplay.setText("0");
            setFlag();
        }
        else{
        totalFirst= Double.parseDouble(txtDisplay.getText() );   
        String showDisplay= txtDisplay.getText()+btnMul.getText();
            txtDisplay.setText(showDisplay);
             getOperator('x' );
             } 
             deactivateFlag();
    }//GEN-LAST:event_btnMulActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        // TODO add your handling code here:
        clearScreen(); 
        String showDisplay= txtDisplay.getText()+btnSeven.getText();
             txtDisplay.setText(showDisplay);
             
             deactivateFlag();
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        // TODO add your handling code here:
        clearScreen(); 
        String showDisplay= txtDisplay.getText()+btnEight.getText();
             txtDisplay.setText(showDisplay);
             
             deactivateFlag();
    }//GEN-LAST:event_btnEightActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        // Button name wrongly named jButton11
        clearScreen(); 
        String showDisplay= txtDisplay.getText()+jButton11.getText();
             txtDisplay.setText(showDisplay);
             
             deactivateFlag();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        // TODO add your handling code here:
        String initString=txtDisplay.getText();
         char firstIndex=initString.charAt(0) ;
        if(firstIndex== 's'   ){
            txtDisplay.setText("0");
            setFlag();
        }else if(firstIndex== 'c' ){
            txtDisplay.setText("0");
            setFlag();
        }else if(firstIndex== 'l' ){
            txtDisplay.setText("0");
            setFlag();
        } else if(initString=="0" ){
            txtDisplay.setText("0");
            setFlag();
        } else if(firstIndex== '0' ){
            txtDisplay.setText("0");
            setFlag();
        }
        else{
        totalFirst=Double.parseDouble(txtDisplay.getText() );
        String showDisplay= txtDisplay.getText()+btnSub.getText();
             txtDisplay.setText(showDisplay);
             getOperator('-');
             }
             deactivateFlag();
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        // TODO add your handling code here:
        clearScreen(); 
        String showDisplay= txtDisplay.getText()+btnPoint.getText();
             txtDisplay.setText(showDisplay);
             
             deactivateFlag();
    }//GEN-LAST:event_btnPointActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        // TODO add your handling code here:
        clearScreen(); 
        String showDisplay= txtDisplay.getText()+btnZero.getText();
             txtDisplay.setText(showDisplay);
             
             deactivateFlag();
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnEquActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquActionPerformed
        // TODO add your handling code here:
         if(  txtDisplay.getText()!=""){
                Double result=0.0;
            String showDisplay= txtDisplay.getText() ;
           if(totalFirst.equals(0.0) );
             String testing=showDisplay.
                     substring(showDisplay.indexOf(mathOperator  )/*,
//                     ((totalFirst.toString().length()-1)+(mathOperator+1) )*/ );
                  char[] ret_testing=new char[testing.length()];
                  String totalLast_string="";
         for(int i=1;i<testing.length();i++){
             ret_testing[i]= testing.charAt(i);
             totalLast_string+=ret_testing[i];
         }    
             
             totalLast=Double.parseDouble(totalLast_string);
    result = check_mathOperator(result); 
           String final_result_string=checkDecimal(result.toString());
             txtDisplay.setText ( final_result_string/*result.toString()*/);
             totalFirst=0.0;
             totalLast=0.0;
     setFlag();
      
         }    
    }//GEN-LAST:event_btnEquActionPerformed

    private static String checkDecimal(String result ){
             char[] ret_result=new char[result.length()];
                 // String totalLast_string="";
           String last_result_string="";
           int counter=0;
         for(int i=0;i<result.length();i++){
             ret_result[i]= result.charAt(i);
             last_result_string+=ret_result[i];
                
        } 
         return last_result_string;
    }  
    private Double check_mathOperator(Double result) {
        // String show=showDisplay. substring(mathOperator, showDisplay.length()-1);
        // totalLast=Double.parseDouble(show );
        
        switch(mathOperator){
            case '/':
                result =totalFirst/totalLast;
                break;
            case 'x':
                result =totalFirst*totalLast;
                break;
            case '-':
                result =totalFirst-totalLast;
                break;
            case '+':
                result =totalFirst+totalLast;
                break;
                
        }
        return result;
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String initString=txtDisplay.getText();
             char firstIndex=initString.charAt(0) ;
        if(firstIndex== 's'   ){
            txtDisplay.setText("0");
            setFlag();
        }else if(firstIndex== 'c' ){
            txtDisplay.setText("0");
            setFlag();
        }else if(firstIndex== 'l' ){
            txtDisplay.setText("0");
            setFlag();
        } else if(initString=="0" ){
            txtDisplay.setText("0");
            setFlag();
        } else if(firstIndex== '0' ){
            txtDisplay.setText("0");
            setFlag();
        }
        else{
        totalFirst=Double.parseDouble(txtDisplay.getText() );
       String showDisplay= txtDisplay.getText() +btnAdd.getText();
             txtDisplay.setText(showDisplay);
             getOperator('+');
              }
             deactivateFlag();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSineActionPerformed
        // TODO add your handling code here:
        String string_sine=txtDisplay.getText();
        char firstIndex=string_sine.charAt(0) ;
        if(firstIndex== 's'   ){
            txtDisplay.setText("0");
        }else if(firstIndex== 'c' ){
            txtDisplay.setText("1");
        }else if(firstIndex== 'l' ){
            txtDisplay.setText("0");
        } else if(string_sine=="0" ){
            txtDisplay.setText("sin()");
        } 
        else{
        long long_sine= (long)
                Math.round(Math.sin(Double.parseDouble(string_sine) ));
        txtDisplay.setText("sin(" +txtDisplay.getText()+  ")="+long_sine+"");
       } 
    }//GEN-LAST:event_btnSineActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        // TODO add your handling code here: 
        String string_cosine=txtDisplay.getText();
        char firstIndex=string_cosine.charAt(0) ;
        if(firstIndex== 's'   ){
            txtDisplay.setText("0");
        }else if(firstIndex== 'c' ){
            txtDisplay.setText("1");
        }else if(firstIndex== 'l' ){
            txtDisplay.setText("0");
        } else if(string_cosine=="0" ){
            txtDisplay.setText("sin()");
        } 
        else{
        long long_cosine= (long)
                Math.round(Math.cos(Double.parseDouble(string_cosine) ));
        txtDisplay.setText("cos(" +txtDisplay.getText()+  ")="+long_cosine+"");
       } 
        setFlag();  
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        String string_log=txtDisplay.getText();
       char firstIndex=string_log.charAt(0) ;
        if(firstIndex== 's'   ){
            txtDisplay.setText("0");
        }else if(firstIndex== 'c' ){
            txtDisplay.setText("1");
        }else if(firstIndex== 'l' ){
            txtDisplay.setText("0");
        } else if(string_log=="0" ){
            txtDisplay.setText("sin()");
        } 
        else{ 
        long long_log= (long)
                Math.round(Math.sin(Double.parseDouble(string_log) ));
        txtDisplay.setText("log(" +txtDisplay.getText()+  ")="+long_log+"");
        }
          setFlag();
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnCLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLActionPerformed
        // TODO add your handling code here:
        txtDisplay.setText("0");
        
        
        setFlag();
    }//GEN-LAST:event_btnCLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCL;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqu;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMul;
    private javax.swing.JPanel btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSine;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton jButton11;
    private javax.swing.JTextField txtDisplay;
    private javax.swing.JTextField txtDisplayOne;
    // End of variables declaration//GEN-END:variables
}
